### PR TITLE
README updated

### LINKED ISSUE #1: update README
add some content

### PR DESCRIPTION
**Pull request by gedev008**
added some content
fix #1

### CODE REVIEW

**Comment by NiKHiLkr23** [comment]
@Gibworkbot tip 5 @gedev008

**Comment by NiKHiLkr23** [comment]
Make sure you are a contributor to this repository.

**Comment by NiKHiLkr23** [comment]
@Gibworkbot tip 5 @gedev008

**Comment by gedev008** [comment]
@gibworkbot tip 5 @NiKHiLkr23

**Comment by NiKHiLkr23** [comment]
Make sure you are a contributor to this repository.

**Comment by gedev008** [comment]
@gibworkbot tip 5 @NiKHiLkr23

**Comment by NiKHiLkr23** [comment]
🎉 @NiKHiLkr23 is getting tipped via <a href='https://stage.tip.gib.work/t/wFANvwSnB0I0gUuT4_6S6eLf' target='_blank'>Gibtips </a> by @NiKHiLkr23 
```text
How does it work?
1- @gedev008 clicks the Gibtips link and funds the escrow.
2- @NiKHiLkr23 clicks the Gibtips link and claims the tip.
```
https://stage.tip.gib.work/t/wFANvwSnB0I0gUuT4_6S6eLf

**Comment by gedev008** [comment]
@gibworkbot tip 4 @NiKHiLkr23

**Comment by NiKHiLkr23** [comment]
Make sure you are a contributor to this repository.

**Comment by NiKHiLkr23** [comment]
🎉 @NiKHiLkr23 is getting tipped via <a href='https://stage.tip.gib.work/t/SczL6l_Ek8I5A20WWh828NsB' target='_blank'>Gibtips </a> by @NiKHiLkr23 
```text
How does it work?
1- @gedev008 clicks the Gibtips link and funds the escrow.
2- @NiKHiLkr23 clicks the Gibtips link and claims the tip.
```
https://stage.tip.gib.work/t/SczL6l_Ek8I5A20WWh828NsB

**Pull request closed without merging**
